### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by RafDiol** [jaspreetsidhu3/py_ide#1]
I can see that you have uploaded the executable of your IDE. But github is about uploading the source of your project.The source of your project includes your python files (.py).If the .py files are not included there is no way for me to see the code behind the IDE and thus there is no way for me to contribute to this project.

Hope you upload the source code soon.

**Comment by jaspreetsidhu3** [comment]
Hey RafDiol,
Sorry for inconvenience, I have uploaded the source you may check it out.  
Thank you for showing interest for the project.

**Comment by RafDiol** [comment]
Thank you for uploading the source code.I will close the issue now
