### ISSUE TITLE
py_ide works in snakeware?

### ISSUE THREAD

**Issue by ghost** [jaspreetsidhu3/py_ide#7]
Hi all. I would like to know if py_ide will work on [snakeware-os](https://github.com/joshiemoore/snakeware). py_ide works in snakeware?

**Comment by RafDiol** [comment]
Although I have not tested it, I believe that it should work. PyIDE is neither using any external dependencies nor requires networking(something not supported by snakeware-os).

**Comment by ghost** [comment]
Hi RafDiol.  Thank you for feedback. So I tested it and there is no support for things like tkinter, PySimpleGUI, pygobject, PyQt5 or access the internet for install pip. I'll see how I can contribute and help this project(py_ide and snakeware-os). So... please close this issue.
